name: lekec
description: pill dispenser
version: 0.1.2

publish_to: "none"

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  go_router: ^17.0.0
  material_symbols_icons: ^4.2892.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  workmanager: ^0.9.0
  alarm: ^5.1.5
  permission_handler: ^12.0.1
  url_launcher: ^6.3.1
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.4
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/mozart.mp3
    - assets/nokia.mp3
    - assets/one_piece.mp3
    - assets/star_wars.mp3
    - assets/marimba.mp3
